version: "3.8"
services:
    app:
        container_name: app
        build:
            context: https://git
            dockerfile: ./docker/laravel/Dockerfile
        image: app:latest
        #restart: unless-stopped
        working_dir: ${PROJECT_PATH}
        entrypoint: /bin/sh -c "composer install &&
            php artisan key:generate &&
            php artisan migrate &&
            php artisan db:seed &&
            php artisan optimize &&
            php-fpm"
        volumes:
            - .:${PROJECT_PATH}
        networks:
            - ltweb-network
        depends_on:
            - postgres
    web:
        container_name: web
        image: nginx:latest
        #restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - .:${PROJECT_PATH}
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - ltweb-network
        depends_on:
            - app

    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            PGDATA: /data/postgres
        volumes:
            - ltweb-database:/data/postgres
            - ltweb-database:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - ltweb-network
        #restart: unless-stopped

networks:
    ltweb-network:
        driver: bridge

volumes:
    ltweb-database:
        driver: local
