version: "3.8"
services:
    app:
        container_name: app
        build:
            args:
                user: tung
                uid: 1000
            context: ./
            dockerfile: ./docker/laravel/Dockerfile
        image: bitnami/laravel:latest
        restart: unless-stopped
        working_dir: ${PROJECT_PATH}
        volumes:
            - .:${PROJECT_PATH}
            #- ./docker/laravel/php.ini:/usr/local/etc/php/php.ini-development
        networks:
            - ltweb-network

    web:
        container_name: web
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - .:${PROJECT_PATH}
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - ltweb-network

    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            PGDATA: /data/postgres
        volumes:
            - ltweb-database:/data/postgres
            - ltweb-database:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - ltweb-network
        restart: unless-stopped

networks:
    ltweb-network:
        driver: bridge

volumes:
    ltweb-database:
        driver: local
