version: "3.8"
services:
    api:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: api:latest
        ports:
            -   "8443:8443"
        env_file:
            -   .env